from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import HTMLResponse
import requests
import hmac
import hashlib
import json
import base64
import logging

from app.config import settings
from app.supabase_client import upsert_user
from app.utils import parse_oauth_state
from app.youtube_client import fetch_credentials, serialize_credentials
from app.admin.api import router as admin_router
from app.admin.queue_worker import start_queue_worker
from app.admin.scheduler import start_admin_scheduler

logger = logging.getLogger(__name__)

app = FastAPI(title="YouTube Auto Bot API")
app.include_router(admin_router)


@app.on_event("startup")
def on_startup() -> None:
    start_queue_worker()
    start_admin_scheduler()


@app.get("/health")
def health_check():
    return {"status": "healthy", "service": "YouTube Auto Bot API", "admin_system": "active"}


# ---------------------------------------------------------------------------
# OAuth helpers
# ---------------------------------------------------------------------------

def _is_admin_state(state: str) -> bool:
    """Check if the OAuth state was generated by the admin system."""
    try:
        parts = state.split(".")
        if len(parts) == 2:
            return True
    except Exception:
        pass
    return False


def _parse_admin_state(state: str) -> dict:
    """Parse admin OAuth state (base64_json.signature)."""
    b64_payload, signature = state.split(".", 1)
    expected = hmac.new(settings.secret_key.encode(), b64_payload.encode(), hashlib.sha256).hexdigest()[:16]
    if not hmac.compare_digest(expected, signature):
        raise ValueError("Invalid admin state signature")
    payload_json = base64.urlsafe_b64decode(b64_payload + "=" * (4 - len(b64_payload) % 4)).decode()
    return json.loads(payload_json)


# ---------------------------------------------------------------------------
# OAuth callback (supports both Telegram bot and admin system)
# ---------------------------------------------------------------------------

@app.get("/oauth2callback", response_class=HTMLResponse)
def oauth2callback(request: Request, code: str = Query(None), state: str = Query(None), error: str = Query(None)):
    try:
        if error:
            raise HTTPException(status_code=400, detail=f"OAuth authorization failed: {error}")

        if not code or not state:
            raise HTTPException(status_code=400, detail="Missing OAuth code or state")

        # Handle admin-system OAuth connections
        if _is_admin_state(state):
            admin_state = _parse_admin_state(state)
            admin_id = admin_state.get("admin_id")
            label = admin_state.get("label", "Unlabeled")
            credentials = fetch_credentials(str(request.url))
            encrypted = serialize_credentials(credentials)
            # Create youtube_channels row
            from app.admin import db as admin_db
            created = admin_db.create_youtube_channel({
                "label": label,
                "oauth_credentials": encrypted,
                "status": "connected",
                "owner_admin_id": admin_id,
                "scopes": [
                    "https://www.googleapis.com/auth/youtube.upload",
                    "https://www.googleapis.com/auth/youtube.readonly",
                ],
            })
            return HTMLResponse(
                content=f"""
                <h1>✅ YouTube Channel Connected!</h1>
                <p>Label: <strong>{label}</strong></p>
                <p>Channel ID in system: <code>{created.get('id')}</code></p>
                <p>You can close this window and return to the admin panel.</p>
                """,
                status_code=200,
            )

        # Legacy Telegram bot OAuth
        telegram_id = parse_oauth_state(state)
        credentials = fetch_credentials(str(request.url))
        encrypted = serialize_credentials(credentials)
        upsert_user(str(telegram_id), oauth_credentials=encrypted, is_connected=True)
        
        # Send Telegram notification
        try:
            url = f"https://api.telegram.org/bot{settings.telegram_token}/sendMessage"
            requests.post(url, json={"chat_id": str(telegram_id), "text": "✅ YouTube channel connected! You can now use /download to upload videos."})
        except Exception as notify_err:
            logger.warning(f"Failed to send notification: {notify_err}")

        return HTMLResponse(
            content="<h1>Connected!</h1><p>Your YouTube channel is now linked to the bot. You can return to Telegram.</p>",
            status_code=200,
        )
    except Exception as e:
        logger.exception("OAuth callback error")
        import traceback
        return HTMLResponse(
            content=f"<h1>Error</h1><p>Failed to connect: {str(e)}</p><pre>{traceback.format_exc()}</pre>",
            status_code=500,
        )
