-- =====================================================================
-- Scalable Admin System Schema
-- Run in Supabase SQL Editor (idempotent).
-- =====================================================================

-- Shared updated_at trigger helper
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- ---------------------------------------------------------------------
-- 1. admin_users  (RBAC)
--    roles: super_admin | admin | operator | viewer
-- ---------------------------------------------------------------------
create table if not exists public.admin_users (
    id              bigint generated by default as identity primary key,
    email           text unique not null,
    telegram_id     text unique,
    password_hash   text,                       -- bcrypt; nullable when SSO/Telegram-only
    api_key_hash    text,                       -- optional machine-to-machine key (hashed)
    full_name       text,
    role            text not null default 'viewer'
                       check (role in ('super_admin','admin','operator','viewer')),
    is_active       boolean not null default true,
    last_login_at   timestamptz,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);
create index if not exists idx_admin_users_role on public.admin_users(role);
drop trigger if exists trg_admin_users_updated_at on public.admin_users;
create trigger trg_admin_users_updated_at before update on public.admin_users
for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 2. source_channels
--    A "source" to copy content FROM (e.g. a YouTube channel URL).
-- ---------------------------------------------------------------------
create table if not exists public.source_channels (
    id              bigint generated by default as identity primary key,
    name            text not null,
    source_type     text not null default 'youtube'
                       check (source_type in ('youtube','rss','custom')),
    source_url      text not null,
    external_id     text,                        -- channel_id, handle, etc.
    fetch_limit     int  not null default 50,
    content_filter  text default 'shorts'
                       check (content_filter in ('shorts','videos','both')),
    is_active       boolean not null default true,
    metadata        jsonb not null default '{}'::jsonb,
    created_by      bigint references public.admin_users(id) on delete set null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);
create index if not exists idx_source_channels_active on public.source_channels(is_active);
create unique index if not exists uq_source_channels_url on public.source_channels(source_url);
drop trigger if exists trg_source_channels_updated_at on public.source_channels;
create trigger trg_source_channels_updated_at before update on public.source_channels
for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 3. youtube_channels
--    A connected YouTube account (destination to publish TO).
--    OAuth tokens are encrypted with Fernet in `oauth_credentials`.
-- ---------------------------------------------------------------------
create table if not exists public.youtube_channels (
    id                  bigint generated by default as identity primary key,
    label               text not null,               -- friendly name shown in UI
    youtube_channel_id  text,                        -- UCxxxx (from API)
    handle              text,                        -- @handle
    email               text,                        -- authorized gmail (metadata only)
    oauth_credentials   text not null,               -- Fernet-encrypted JSON
    scopes              text[] default array[
                          'https://www.googleapis.com/auth/youtube.upload',
                          'https://www.googleapis.com/auth/youtube.readonly'
                        ],
    status              text not null default 'connected'
                           check (status in ('connected','expired','revoked','disabled')),
    daily_quota_limit   int not null default 6,      -- uploads/day soft cap (YT default ~6)
    uploads_today       int not null default 0,
    quota_reset_at      timestamptz,
    last_used_at        timestamptz,
    metadata            jsonb not null default '{}'::jsonb,
    owner_admin_id      bigint references public.admin_users(id) on delete set null,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);
create unique index if not exists uq_youtube_channels_channel_id
    on public.youtube_channels(youtube_channel_id)
    where youtube_channel_id is not null;
create index if not exists idx_youtube_channels_status on public.youtube_channels(status);
drop trigger if exists trg_youtube_channels_updated_at on public.youtube_channels;
create trigger trg_youtube_channels_updated_at before update on public.youtube_channels
for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 4. channel_mappings  (MANY-to-MANY: source_channel <-> youtube_channel)
--    A single source can push to many YT accounts; one YT account
--    can subscribe to many sources.  Per-mapping publishing rules.
-- ---------------------------------------------------------------------
create table if not exists public.channel_mappings (
    id                  bigint generated by default as identity primary key,
    source_channel_id   bigint not null references public.source_channels(id) on delete cascade,
    youtube_channel_id  bigint not null references public.youtube_channels(id) on delete cascade,
    is_active           boolean not null default true,
    visibility          text not null default 'public'
                           check (visibility in ('public','unlisted','private')),
    schedule_cron       text,                        -- cron; null = on-demand only
    schedule_timezone   text not null default 'UTC',
    max_per_run         int  not null default 1,     -- videos pushed per scheduled tick
    priority            int  not null default 100,   -- lower = higher priority
    title_template      text,                        -- e.g. '{title}'
    description_template text,
    tag_template        text,                        -- comma-sep
    last_run_at         timestamptz,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now(),
    unique (source_channel_id, youtube_channel_id)
);
create index if not exists idx_mappings_source on public.channel_mappings(source_channel_id);
create index if not exists idx_mappings_youtube on public.channel_mappings(youtube_channel_id);
create index if not exists idx_mappings_active on public.channel_mappings(is_active);
drop trigger if exists trg_channel_mappings_updated_at on public.channel_mappings;
create trigger trg_channel_mappings_updated_at before update on public.channel_mappings
for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 5. upload_queue
--    The persistent job queue (download -> upload) with retries.
-- ---------------------------------------------------------------------
create table if not exists public.upload_queue (
    id                  bigint generated by default as identity primary key,
    mapping_id          bigint references public.channel_mappings(id) on delete set null,
    source_channel_id   bigint references public.source_channels(id) on delete set null,
    youtube_channel_id  bigint references public.youtube_channels(id) on delete set null,
    source_video_id     text,                        -- upstream YouTube id
    video_url           text not null,
    title               text,
    description         text,
    visibility          text not null default 'public',
    status              text not null default 'pending'
                           check (status in ('pending','scheduled','downloading',
                                             'uploading','done','failed','cancelled','retrying')),
    attempts            int  not null default 0,
    max_attempts        int  not null default 5,
    scheduled_at        timestamptz not null default now(),
    started_at          timestamptz,
    finished_at         timestamptz,
    next_retry_at       timestamptz,
    result_url          text,
    result_video_id     text,
    error_message       text,
    priority            int  not null default 100,
    created_by          bigint references public.admin_users(id) on delete set null,
    created_at          timestamptz not null default now(),
    updated_at          timestamptz not null default now()
);
create index if not exists idx_upload_queue_status on public.upload_queue(status);
create index if not exists idx_upload_queue_scheduled on public.upload_queue(scheduled_at);
create index if not exists idx_upload_queue_yt on public.upload_queue(youtube_channel_id);
create index if not exists idx_upload_queue_src on public.upload_queue(source_channel_id);
create unique index if not exists uq_upload_queue_dedup
    on public.upload_queue(mapping_id, source_video_id)
    where source_video_id is not null;
drop trigger if exists trg_upload_queue_updated_at on public.upload_queue;
create trigger trg_upload_queue_updated_at before update on public.upload_queue
for each row execute function public.set_updated_at();


-- ---------------------------------------------------------------------
-- 6. upload_logs   (per-job event trail for analytics)
-- ---------------------------------------------------------------------
create table if not exists public.upload_logs (
    id          bigint generated by default as identity primary key,
    queue_id    bigint references public.upload_queue(id) on delete cascade,
    level       text not null default 'info'
                   check (level in ('debug','info','warning','error')),
    event       text not null,                        -- e.g. 'download_started'
    message     text,
    context     jsonb not null default '{}'::jsonb,
    created_at  timestamptz not null default now()
);
create index if not exists idx_upload_logs_queue on public.upload_logs(queue_id);
create index if not exists idx_upload_logs_level on public.upload_logs(level);
create index if not exists idx_upload_logs_event on public.upload_logs(event);


-- ---------------------------------------------------------------------
-- 7. admin_audit_log   (who-did-what)
-- ---------------------------------------------------------------------
create table if not exists public.admin_audit_log (
    id          bigint generated by default as identity primary key,
    admin_id    bigint references public.admin_users(id) on delete set null,
    action      text not null,                        -- e.g. 'create_source_channel'
    target_type text,                                 -- 'source_channel'|'youtube_channel'|...
    target_id   text,
    details     jsonb not null default '{}'::jsonb,
    ip_address  text,
    user_agent  text,
    created_at  timestamptz not null default now()
);
create index if not exists idx_audit_admin on public.admin_audit_log(admin_id);
create index if not exists idx_audit_action on public.admin_audit_log(action);
create index if not exists idx_audit_created on public.admin_audit_log(created_at desc);


-- ---------------------------------------------------------------------
-- 8. dedup table for already-seen source videos
-- ---------------------------------------------------------------------
create table if not exists public.seen_source_videos (
    id                 bigint generated by default as identity primary key,
    source_channel_id  bigint not null references public.source_channels(id) on delete cascade,
    source_video_id    text not null,
    first_seen_at      timestamptz not null default now(),
    unique (source_channel_id, source_video_id)
);


-- ---------------------------------------------------------------------
-- 9. analytics materialised view-ish stats helper
-- ---------------------------------------------------------------------
create or replace view public.v_upload_stats as
select
    date_trunc('day', created_at) as day,
    youtube_channel_id,
    source_channel_id,
    status,
    count(*) as total
from public.upload_queue
group by 1, 2, 3, 4;

-- Disable RLS on admin tables – access gated by service key + app-level RBAC.
alter table public.admin_users        disable row level security;
alter table public.source_channels    disable row level security;
alter table public.youtube_channels   disable row level security;
alter table public.channel_mappings   disable row level security;
alter table public.upload_queue       disable row level security;
alter table public.upload_logs        disable row level security;
alter table public.admin_audit_log    disable row level security;
alter table public.seen_source_videos disable row level security;
