-- Create app_settings table used by admin limits/config.
-- Run this in Supabase SQL Editor.

create table if not exists public.app_settings (
  id bigint generated by default as identity primary key,
  setting_name text unique not null,
  setting_value text,
  description text,
  updated_at timestamptz not null default now()
);

-- Optional: keep updated_at fresh on updates.
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_app_settings_updated_at on public.app_settings;
create trigger trg_app_settings_updated_at
before update on public.app_settings
for each row
execute function public.set_updated_at();

-- Seed defaults used by bot.py plan/config logic.
insert into public.app_settings (setting_name, setting_value, description)
values
  ('default_quality', '"Best Available"', 'Default quality for new users'),
  ('default_visibility', '"unlisted"', 'Default visibility for new jobs'),
  ('auto_cleanup', 'true', 'Enable cleanup of temporary files'),
  ('max_concurrent_downloads', '3', 'Worker concurrency cap'),
  ('free_daily_limit', '3', 'Daily jobs for free plan'),
  ('paid_daily_limit', '30', 'Daily jobs for paid plan'),
  ('free_max_pending_jobs', '1', 'Pending queue cap for free plan'),
  ('paid_max_pending_jobs', '5', 'Pending queue cap for paid plan'),
  ('paid_user_ids', '""', 'Comma-separated Telegram IDs with manual paid access'),
  ('paid_user_expiry', '{}', 'JSON map: telegram_id -> ISO datetime expiry')
on conflict (setting_name) do nothing;
